import { z } from "zod";
import { dateSchema, moneySchema, optionalDateSchema, optionalMoneySchema, pagingSchema, rateSchema } from "../../shared/money";
import { idSchema, optionalText, requiredText } from "../../shared/validation";

// PROVISIONAL status list (open question Q7). Must match projects_status_ck.
export const PROJECT_STATUSES = ["NEW", "IN_PROGRESS", "COMPLETED", "CANCELLED"] as const;
export type ProjectStatus = (typeof PROJECT_STATUSES)[number];

// Derived by v_project_financials, never stored.
export const INVOICE_STATES = ["NOT_READY", "READY_FOR_INVOICE", "NO_INVOICE_REQUIRED", "NOT_APPLICABLE"] as const;
export type InvoiceState = (typeof INVOICE_STATES)[number];

const clientId = z.string({ error: "Client is required." }).regex(/^[1-9]\d{0,17}$/, "Select a client.");

const projectFields = {
  clientId,
  description: requiredText("Job description", 1000),
  jobDate: dateSchema("Job date"),
  lpoNumber: optionalText("LPO number", 100),
  lpoDate: optionalDateSchema("LPO date"),
  jobValue: moneySchema("Job value", { allowZero: true }),
  vatRate: rateSchema("VAT rate"),
  budgetAmount: optionalMoneySchema("Budget"),
  notes: optionalText("Notes", 2000),
};

// The job number is generated by the API and the VAT amount and grand value
// are calculated by PostgreSQL, so none of them is accepted here.
export const createProjectSchema = z.strictObject({
  clientId: projectFields.clientId,
  description: projectFields.description,
  jobDate: projectFields.jobDate,
  lpoNumber: projectFields.lpoNumber.optional(),
  lpoDate: projectFields.lpoDate.optional(),
  jobValue: projectFields.jobValue,
  // Left out: the default rate from app_settings is used.
  vatRate: projectFields.vatRate.optional(),
  budgetAmount: projectFields.budgetAmount.optional(),
  notes: projectFields.notes.optional(),
});

// Every field optional: a field that is left out is not changed.
// Status is changed through its own route.
export const updateProjectSchema = z
  .strictObject({
    clientId: projectFields.clientId.optional(),
    description: projectFields.description.optional(),
    jobDate: projectFields.jobDate.optional(),
    lpoNumber: projectFields.lpoNumber.optional(),
    lpoDate: projectFields.lpoDate.optional(),
    jobValue: projectFields.jobValue.optional(),
    vatRate: projectFields.vatRate.optional(),
    budgetAmount: projectFields.budgetAmount.optional(),
    notes: projectFields.notes.optional(),
  })
  .refine((value) => Object.values(value).some((field) => field !== undefined), "Provide at least one field to update.");

export const changeProjectStatusSchema = z.strictObject({
  status: z.enum(PROJECT_STATUSES, { error: "Select a valid status." }),
  // Only used when completing. Left out: today.
  completedDate: optionalDateSchema("Completion date").optional(),
});

export const listProjectsSchema = z.object({
  search: z.string().trim().max(200).optional(),
  status: z.enum(PROJECT_STATUSES).optional(),
  invoiceState: z.enum(INVOICE_STATES).optional(),
  clientId: idSchema.optional(),
  ...pagingSchema,
});

export type CreateProjectInput = z.infer<typeof createProjectSchema>;
export type UpdateProjectInput = z.infer<typeof updateProjectSchema>;
export type ChangeProjectStatusInput = z.infer<typeof changeProjectStatusSchema>;
export type ListProjectsQuery = z.infer<typeof listProjectsSchema>;
